---
title: "Chapter_8"
output: html_document
---

```{r}
library(readr)
library(magrittr)
library(tibble)
library(dplyr)
library(tidyverse)
library(lubridate)
library(stringr)
```

```{r}
storms <- read_csv("../Part_Two/Data/StormEvents_details-ftp_v1.0_d2017_c20190817.csv.gz",
                   col_names = TRUE) %>%
  select(BEGIN_DATE_TIME, END_DATE_TIME, EPISODE_ID:STATE_FIPS, EVENT_TYPE:CZ_NAME, SOURCE,
         BEGIN_LAT:END_LAT) %>%
  mutate(BEGIN_DATE_TIME = dmy_hms(BEGIN_DATE_TIME),
         END_DATE_TIME = dmy_hms(END_DATE_TIME),
         STATE = str_to_title(STATE),
         CZ_NAME = str_to_title(CZ_NAME)) %>%
  filter(CZ_TYPE == "C") %>%
  select(-CZ_TYPE) %>% 
  mutate(STATE_FIPS = str_pad(STATE_FIPS, 2, side = "left", pad = "0"),
         CZ_FIPS = str_pad(CZ_FIPS, 3, side = "left", pad = "0")) %>%
  unite(FIPS, STATE_FIPS, CZ_FIPS, sep = "") %>% 
  rename_all(funs(str_to_lower(.))) %>% 
  print()
```

```{r}
data("state")
us_state_info <- tibble(state = state.name, 
                            area = state.area,
                            region = state.region)
```

```{r}
storms_2 <- storms %>% 
  group_by(state) %>% 
  count() %>% 
  ungroup() %>% 
  right_join(us_state_info, by = "state") %>% 
  print()
```
```{r}
storms_plot <- storms_2 %>% 
  ggplot(aes(x = area, y = n)) +
  geom_point(aes(color = region)) +
  labs(x = "Land area (sq, miles)", y = "# of storm events") +
  ggtitle("Storm events 2017")
storms_plot
```

```{r}
library(sf)
library(tigris)
library(scales)
library(tidyverse)
library(viridis)
```
```{r}
co_counties <- counties(state = "CO", cb = TRUE, class="sf")
co_storms <- storms %>% 
  filter(state == "Colorado") %>% 
  group_by(fips) %>% 
  count() %>% 
  ungroup() %>% 
  print()

co_count_events <- co_counties %>% 
  mutate(fips = paste(STATEFP, COUNTYFP, sep = "")) %>% 
  full_join(co_storms, by = "fips") %>% 
  mutate(n = ifelse(!is.na(n), n, 0)) %>% 
  print()
```


```{r}
ggplot() +
  geom_sf(data = co_count_events, aes(fill = n)) +
  scale_fill_viridis(name = "Number of events\n(2017)")

```

```{r}
larimer <- co_counties %>% 
  filter(NAME == "Larimer") %>% 
  print()

```

