---
title: "Homework_4"
output: html_document
---
Load required libraries.
```{r, warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(tidyr)
library(broom)
library(purrr)
library(scales)
```
Read data in, combine city/state columns. 
```{r, warning=FALSE, message=FALSE, error=FALSE}

homicides <- read_csv("homicide-data.csv", col_names = TRUE) %>% 
  as_tibble() %>% 
  unite(col = "city_state", city, state, sep = ",") %>% 
  print()
```
Summary of dispostion of cases (closed by arrest, or not).
```{r, warning=FALSE, message=FALSE, error=FALSE}
unsolved <- homicides %>% 
  mutate(unsolved = disposition != "Closed by arrest") %>% 
  group_by(city_state) %>% 
  summarize(total = n(), total_unsolved = sum(unsolved)) %>%
  select(city_state, total_unsolved, total) %>% 
  print()
```
Making frame work for map2 call in which prop.test is applied to each row (city_state). 
```{r, warning=FALSE, message=FALSE, error=FALSE}
baltimore <- unsolved[3,]
balt_prop <- prop.test(baltimore$total_unsolved, baltimore$total) %>% 
  tidy()

balt_prop %>% 
  select(estimate, conf.high, conf.low)
```
Applying prop.test and tidying output of statistical analysis. 
```{r, warning=FALSE, message=FALSE, error=FALSE}
estimates_unsolved <- unsolved %>% 
  mutate(results = map2(total_unsolved, total, ~prop.test(.x, .y))) %>% 
  mutate(results = map(results, ~tidy(.x))) %>% 
  unnest(.drop = TRUE) %>% 
  select(city_state, estimate, conf.low, conf.high) %>% 
  print()
```
Mimicking graph. 
```{r, warning=FALSE, message=FALSE, error=FALSE, fig.width=5, fig.height=10}
estimates_unsolved %>%
  slice(-49) %>% 
  ggplot(aes(x = estimate, y = factor(city_state, levels = city_state[order(estimate)]))) +
  geom_point(color = "white") +
  geom_errorbarh(aes(xmax = conf.high, xmin = conf.low, height = 0), color = "white") +
  ggtitle("Unsolved homicides by city", subtitle = "Bars show 95% confidence interval") +
  labs(x = "Percent of homicides that are unsolved", y = "") +
  theme(plot.subtitle = element_text(face = "bold")) +
  theme_dark() +
  scale_x_continuous(labels = percent)
```



