---
title: "Week_8"
author: "Burton Karger"
date: "10/14/2019"
output: html_document
---

```{r}
library(ggplot2)
library(ggfortify)
library(broom)
library(dlnm)
data("chicagoNMMAPS")
chic <- chicagoNMMAPS
chic
mod_1 <- lm(dptp ~ temp, data = chic)
tidy(mod_1)

augment(mod_1) %>% 
  ggplot(aes(x = temp, y = dptp)) + 
  geom_point() +
  geom_line(aes(y = .fitted), color = "red")

autoplot(mod_1)

mod_2 <- glm(dptp ~ temp, data = chic)
tidy(mod_2)

mod_3 <- lm(pm10 ~ dow, data = chic)
tidy(mod_3)

anova(mod_3)

summer <- chic %>%
  mutate(month = month(date, label = TRUE)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug"))
summer %>% 
  slice(1:3)

resp_deaths <- glm(resp ~ temp, data = summer, family = poisson(link = "log"))
tidy(resp_deaths)

augment(resp_deaths) %>% 
  ggplot(aes(x = temp, y= resp)) +
  geom_point()+
  geom_point(aes(y = exp(.fitted), color = "red")) +
  geom_smooth()
```
```{r}
library(microbiome)
data(atlas1006)

atlas1006 %>% 
  get_sample() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "species") %>% 
  pivot_longer(- species, 
               names_to = "sample",
               values_to = "prevalence") %>% 
  group_by(species) %>% 
  nest() %>% 
  mutate(mean_prevalence = map(data, ~ .x %>% 
                                 pluck("prevalence") %>% 
                                 mean())) %>% 
  unnest(mean_prevalence)
```
In course 7.8.6
```{r}
library(nycflights13)
library(tidyverse)
library(dlnm)

flights_1 <- nycflights13::flights %>% 
  select(dep_delay, hour, carrier, origin) %>% 
  filter(origin == "LGA",
         dep_delay != is.na(dep_delay)) %>% 
  mutate(late_dep = dep_delay > 15)

flights_1 %>% 
  purrr::pluck("late_dep") %>% 
  mean()

nycflights13::flights %>% 
  select(dep_delay, hour, carrier, origin) %>% 
  filter(origin == "LGA",
         dep_delay != is.na(dep_delay)) %>% 
  mutate(late_dep = dep_delay > 15) %>% 
  group_by(hour) %>% 
  summarize(prob_late = mean(late_dep)) %>% 
  ggplot(aes(x = hour, y = prob_late)) +
  geom_point()

glm(late_dep ~ hour, data = flights_1, family = binomial(link = "logit")) %>%
  tidy() %>% 
  filter(term == "hour") %>% 
  mutate(or = exp(estimate))

nested_flights <- flights_1 %>% 
  group_by(carrier) %>% 
  nest() %>% 
  mutate(glm_result = map(data, ~glm(late_dep ~ hour, data = .x, family = binomial(link = "logit")))) %>% 
  mutate(glm_reults_tidy = map(glm_result, ~tidy(.x))) %>% 
  select(-data, -glm_result) %>% 
  unnest(glm_reults_tidy) %>% 
  filter(term == "hour") %>% 
  mutate(or = exp(estimate))

```

