---
title: "Week_7"
author: "Burton Karger"
date: "10/9/2019"
output: html_document
---

```{r}
library(microbiome)
library(knitr)
library(tidyverse)
data("atlas1006")
print(atlas1006)

#provides information about samples obtained from each subject
pseq <- get_variable(atlas1006) %>% 
  as.tibble() %>% 
  select(-DNA_extraction_method)
  
  
pseq


pseq %>% 
  ggplot(aes(x = bmi_group, y = diversity, color = sex))+
  facet_wrap("nationality") +
  geom_boxplot()
```
```{r}
library(babynames)
library(stringr)
library(tidyverse)
library(purrr)
library(scales)
df <- babynames %>% 
  mutate(name = str_sub(name, 1,1)) %>% 
  group_by(name) %>%
  summarize(n = n/sum(n))%>% 
  ungroup() %>% 
  mutate(proportion = sum(n)) %>% 
  arrange(desc(proportion)) 

df  

student_list <- tibble(name = c("Burton", "Caroline", "Chaoyu", "Collin",
                                    "Daniel", "Eric", "Erin", "Heather",
                                    "Jacob", "Jessica", "Khum", "Kyle",
                                    "Matthew", "Molly", "Nikki", "Rachel",
                                    "Sere",  "Shayna", "Sherry", "Sunny"))
student_list <- student_list %>% 
  mutate(first_letter = str_sub(name, 1, 1))
student_list %>% 
  mutate(name = str_extract(name, ".")) %>% 
  group_by(name) %>% 
  count() %>% 
  ungroup() %>%
  mutate(proportion = n/sum(n)) %>% 
  arrange(desc(proportion)) 

c_or_s <- babynames %>% 
  mutate(first_letter = str_sub(name, 1, 1),
         c_or_s = first_letter %in% c("C", "S"))
c_or_s %>% 
  select(name, first_letter, c_or_s) %>% 
  slice(1:5)
c_or_s %>% 
  group_by(c_or_s) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(prop = n / sum(n))

prop.test(x = c(268910, 7), n = c(1655755, 20))
```



